### ISSUE TITLE
对比crp 构建太慢的

### ISSUE THREAD

**Issue by zuoge85** [AliyunCodePipeline/issues#12]
- 构建没有时间，不方便观察到底卡哪儿了
- 构建在长期卡在 ，
` /bin/bash -c "chmod +x /tmp/hudson823654282958931240.sh;chown -R jenkins:jenkins /home/jenkins;su -s /bin/sh -c /tmp/hudson823654282958931240.sh jenkins"`
- 卡的时候java 进程堆栈，看上去是进程通讯
```
"/bin/bash -c chmod +x /tmp/hudson823654282958931240.sh;chown -R jenkins:jenkins /home/jenkins;su -s /bin/sh -c /tmp/hudson823654282958931240.sh jenkins: stdout copier" Id=81 Group=main RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	-  locked java.lang.UNIXProcess$ProcessPipeInputStream@8e9a5d5
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at hudson.util.StreamCopyThread.run(StreamCopyThread.java:60)
```

另外一个进程:

```
"Channel reader thread: channel" Id=11 Group=main RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	-  locked java.io.BufferedInputStream@298f905b
	at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:86)
	at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
```

以上都是纯mvn构建，并且关闭了测试

- 构建比crp 慢太多。
![default](https://user-images.githubusercontent.com/8085329/29017668-72c96542-7b8a-11e7-82da-6c27010a4ff2.png)
而 cds 构建 用时 

`
构建用时： 16 分 运行于 slave-java-5372bee7581b
`

`
构建用时： 6 分 43 秒 运行于 slave-java-ac9682fa804c
`

建议优化

**Comment by ringtail** [comment]
麻烦再测试下，看下情况是否改善

**Comment by ringtail** [comment]
已优化阿里云Maven加速
