### ISSUE TITLE
部署vue项目失败。时好时坏，特别是晚上10点左右，失败几率很高，白天正常。

### ISSUE THREAD

**Issue by figogao** [AliyunCodePipeline/issues#70]
> node-sass@4.9.4 postinstall /home/jenkins/workspace/DingPortalWebsite/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /home/jenkins/workspace/DingPortalWebsite/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/home/jenkins/workspace/DingPortalWebsite/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp
 verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.9.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp
 verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:80:29)
gyp
 verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:68:19)
gyp
 verb `which` failed     at E (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:13:12)\n    at F (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:68:19)\n    at E (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:80:29)\n    at /home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:89:16\n    at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/index.js:42:5\n    at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp
 verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:89:16
gyp verb
 `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:13:12)
gyp verb 
`which` failed     at F (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp 
verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:13:12)\n    at F (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:68:19)\n    at E (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:80:29)\n    at /home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:89:16\n    at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/index.js:42:5\n    at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/jenkins/workspace/DingPortalWebsite/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/jenkins/workspace/DingPortalWebsite/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/jenkins/workspace/DingPortalWebsite/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/jenkins/workspace/DingPortalWebsite/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System
 Linux 3.10.0-693.2.2.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/home/jenkins/workspace/DingPortalWebsite/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/jenkins/workspace/DingPortalWebsite/node_modules/node-sass
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2018-11-02T02_19_14_495Z-debug.log
Build step '
执行Shell脚本
' marked build as failure

Finished: FAILURE

**Comment by cui-liqiang** [comment]
“verb which failed Error: not found: python”

找不到python？
